const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'vocab-test-'));
const root=path.resolve(__dirname,'..');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url='file://'+path.join(root,'examples/demo.html');
await page.goto(url);await page.evaluate(()=>localStorage.clear());await page.reload();
assert.equal(await page.locator('#total').textContent(),'8');
assert.equal(await page.locator('#answer').isVisible(),false);
await page.locator('#reveal').click();assert.equal(await page.locator('#term').textContent(),'figure out');
await page.locator('#known').click();assert.equal(await page.locator('#learned').textContent(),'1');
await page.reload();assert.equal(await page.locator('#learned').textContent(),'1');
await page.locator('#filter').selectOption('unlearned');assert.match(await page.locator('#position').textContent(),/07/);
await page.locator('#reveal').click();await page.locator('#again').click();
await page.locator('#filter').selectOption('again');assert.match(await page.locator('#position').textContent(),/01 \/ 01/);
await page.locator('#reveal').click();await page.locator('#known').click();assert.match(await page.locator('#sentence').textContent(),/学完/);assert.equal(await page.locator('#reveal').isDisabled(),true);
await page.locator('#list-tab').click();await page.locator('#search').fill('coffee');assert.equal(await page.locator('.word').count(),1);await page.locator('#search').fill('不存在');assert.equal(await page.locator('.word').count(),0);
const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;await download.saveAs(path.join(scratch,'progress.json'));
page.on('dialog',d=>d.accept());await page.locator('#reset').click();assert.equal(await page.locator('#learned').textContent(),'0');
await page.locator('#file').setInputFiles(path.join(scratch,'progress.json'));await page.waitForFunction(()=>document.querySelector('#learned').textContent==='2');
await page.locator('#study-tab').click();await page.locator('#filter').selectOption('all');await page.locator('#shuffle').click();
await page.locator('h1').click();await page.keyboard.press('Space');assert.equal(await page.locator('#answer').isVisible(),true);
await page.keyboard.press('ArrowRight');assert.match(await page.locator('#position').textContent(),/02 \/ 08/);
await page.locator('#reset').click();await page.locator('#filter').selectOption('all');await page.reload();await page.locator('#reveal').click();
await page.screenshot({path:path.join(scratch,'desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(scratch,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked')}})});const p=await blocked.newPage();await p.goto(url);assert.match(await p.locator('#notice').textContent(),/无法读取/);await p.locator('#reveal').click();await p.locator('#known').click();assert.match(await p.locator('#notice').textContent(),/未允许/);assert.equal(await p.locator('#learned').textContent(),'1');
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: flip, rating, persistence, filters, empty state, search, export/import, reset, shuffle, keyboard, mobile overflow, blocked storage, no JS errors');
})().catch(e=>{console.error(e);process.exit(1)});
