const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
const {spawnSync}=require('node:child_process');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'juyouci-browser-'));
const root=path.resolve(__dirname,'..');
(async()=>{
const master=path.join(scratch,'juyouci.html');
fs.copyFileSync(path.join(root,'examples/demo.html'),master);
const second=JSON.parse(fs.readFileSync(path.join(root,'examples/demo.json'),'utf8'));
second.title='原创演示 · 第二词库';second.deck_id='demo:second:zh';
second.cards=second.cards.slice(0,2).map((card,i)=>({...card,term:i?'check in':'look into',answers:[i?'check in':'look into'],targets:[i?'check in':'look into'],sentence:i?'We should check in before the meeting.':'I will look into the missing order tomorrow.',translation:i?'开会前我们应该先签到。':'我明天会查一下丢失的订单。'}));
const secondPack=path.join(scratch,'second.json');fs.writeFileSync(secondPack,JSON.stringify(second));
const merge=spawnSync('python3',[path.join(root,'scripts/build_html.py'),secondPack,master],{encoding:'utf8'});
if(merge.status!==0)throw Error(merge.stderr||merge.stdout||'无法准备多词库页面');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.setOffline(true);await page.goto('file://'+master);
assert.equal(await page.locator('#deck-select option').count(),2);
assert.equal(await page.locator('#practice-mode').inputValue(),'flashcard');
assert.match(await page.locator('#position').textContent(),/学习新词|CARD/);
assert.equal(await page.locator('#sentence').textContent(),'We can figure out the schedule after lunch.');
assert.equal(await page.locator('#answer-block').isVisible(),true);
for(let i=0;i<4;i++)await page.locator('#start').click();
assert.match(await page.locator('#position').textContent(),/回忆词义/);
assert.equal(await page.locator('#self-actions').isVisible(),true);
await page.locator('#reveal').click();assert.equal(await page.locator('#target').textContent(),'figure out');
await page.locator('#again').click();assert.equal(await page.locator('#learned').textContent(),'0');
await page.locator('#filter').selectOption('again');assert.match(await page.locator('#position').textContent(),/回忆词义/);
await page.locator('#practice-mode').selectOption('typed');
assert.match(await page.locator('#position').textContent(),/回忆词义/);
assert.equal(await page.locator('#self-actions').isVisible(),true);
await page.locator('#reveal').click();await page.locator('#known').click();
assert.match(await page.locator('#position').textContent(),/回想英文/);
assert.equal(await page.locator('#typed-actions').isVisible(),true);
await page.locator('#answer-input').fill('FIGURE OUT!');await page.locator('#check').click();
assert.match(await page.locator('#feedback').textContent(),/答对了/);
await page.locator('#continue').click();assert.equal(await page.locator('#learned').textContent(),'1');
await page.reload();assert.equal(await page.locator('#learned').textContent(),'1');
assert.equal(await page.locator('#practice-mode').inputValue(),'typed');
await page.locator('#deck-select').selectOption('demo:second:zh');
assert.equal(await page.locator('#title').textContent(),'原创演示 · 第二词库');
assert.equal(await page.locator('#learned').textContent(),'0');
const dp=page.waitForEvent('download');await page.locator('#export').click();await(await dp).saveAs(path.join(scratch,'progress.json'));
page.on('dialog',d=>d.accept());await page.locator('#reset').click();assert.equal(await page.locator('#learned').textContent(),'0');
await page.locator('#file').setInputFiles(path.join(scratch,'progress.json'));await page.waitForFunction(()=>document.querySelector('#learned').textContent==='0');
await page.locator('#list-tab').click();await page.locator('#search').fill('look into');assert.equal(await page.locator('.word').count(),1);
await page.locator('#search').fill('check in');assert.equal(await page.locator('.word').count(),1);
await page.locator('#study-tab').click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}})});const p=await blocked.newPage();await p.goto('file://'+master);assert.equal(await p.locator('#deck-select option').count(),2);assert.match(await p.locator('#notice').textContent(),/无法读取|未允许/);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: library merge/selection, default self-rating, optional typed recall, shared mode preference, per-deck progress, import/export, offline and narrow layout');
})().catch(e=>{console.error(e);process.exit(1)});
