const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'vocab-test-'));
const root=path.resolve(__dirname,'..');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url='file://'+path.join(root,'examples/demo.html');
await context.setOffline(true);await page.goto(url);
assert.equal(await page.locator('#total').textContent(),'8');
assert.equal(await page.locator('#learn-panel').isVisible(),true);
assert.equal(await page.locator('#recall-panel').isVisible(),false);
assert.equal(await page.locator('#target').textContent(),'figure out');
assert.equal(await page.locator('#sentence mark').textContent(),'figure out');
for(let i=0;i<4;i++)await page.locator('#start').click();
assert.equal(await page.locator('#recall-panel').isVisible(),true);
assert.equal(await page.locator('#learn-panel').isVisible(),false);
assert.equal(await page.locator('#sentence mark').textContent(),'________');
assert.equal(await page.locator('#prompt').textContent(),'弄明白；找到办法');
await page.locator('#answer-input').fill('wrong');await page.locator('#check').click();
assert.match(await page.locator('#feedback').textContent(),/答案：figure out/);
await page.locator('#continue').click();
await page.locator('#filter').selectOption('again');
assert.equal(await page.locator('#prompt').textContent(),'弄明白；找到办法');
await page.locator('#answer-input').fill('FIGURE OUT!');await page.locator('#check').click();
assert.match(await page.locator('#feedback').textContent(),/答对了/);
await page.locator('#continue').click();assert.equal(await page.locator('#learned').textContent(),'1');
await page.reload();assert.equal(await page.locator('#learned').textContent(),'1');
const dp=page.waitForEvent('download');await page.locator('#export').click();await(await dp).saveAs(path.join(scratch,'progress.json'));
page.on('dialog',d=>d.accept());await page.locator('#reset').click();assert.equal(await page.locator('#learned').textContent(),'0');
await page.locator('#file').setInputFiles(path.join(scratch,'progress.json'));await page.waitForFunction(()=>document.querySelector('#learned').textContent==='1');
await page.locator('#list-tab').click();await page.locator('#search').fill('coffee');assert.equal(await page.locator('.word').count(),1);
await page.locator('#study-tab').click();await page.locator('#filter').selectOption('all');await page.locator('#shuffle').click();
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}})});const p=await blocked.newPage();await p.goto(url);assert.match(await p.locator('#notice').textContent(),/无法读取/);await p.locator('#start').click();assert.match(await p.locator('#notice').textContent(),/未允许/);
assert.deepEqual(errors,[]);await browser.close();console.log('Input recall flow and existing browser storage/offline/layout paths');
})().catch(e=>{console.error(e);process.exit(1)});
